### ISSUE TITLE
I would like to document Time::Strptime as a companion module to Time::Moment 

### ISSUE THREAD

**Issue by chansen** [karupanerura/Time-Strptime#1]
I would like to document Time::Strptime as a companion module to Time::Moment, any plans to release a stable version? The paragraph in the documentation that states: **THE SOFTWARE IS IT'S IN ALPHA QUALITY. IT MAY CHANGE THE API WITHOUT NOTICE.** Seems a bit scary ;)

**Comment by karupanerura** [comment]
Sorry for noticing late.
Thank you for your suggestion.

This module works correctly in many cases. (I used it in my works, but I haven't found any problem.)
But, It has still some issues. (#2, #3, #4, #5)
I fixed these issues and I release stable version on next month, maybe.. (Recently, I have no time...)

**Comment by karupanerura** [comment]
@chansen I’m sorry to have kept you waiting.
Version 1.00 is released! https://metacpan.org/release/KARUPA/Time-Strptime-1.00

**Comment by chansen** [comment]
Excellent news! I'll document Time::Strptime as a companion module in Time::Moment.
